### ISSUE TITLE
Doc fix for MacOS users

### ISSUE THREAD

**Issue by malini-kamalambal** [mathieu-benoit/hello-humanitec#1]
Section: https://github.com/mathieu-benoit/hello-humanitec/tree/main/samples/onlineboutique#all-in-once

Issue:
Not sure if its tied to running the commands on mac.
WORKLOADS="cartservice checkoutservice currencyservice emailservice frontend loadgenerator paymentservice productcatalogservice recommendationservice" does not work as expected on mac.Had to change it to 
WORKLOADS=(cartservice checkoutservice currencyservice emailservice frontend loadgenerator paymentservice productcatalogservice recommendationservice)

**Comment by mathieu-benoit** [comment]
Thanks for reporting this issue @malini-kamalambal, much appreciated. I didn't know about that limitation.

Does this below work for you on MacOS:
```
WORKLOADS=(cartservice checkoutservice currencyservice emailservice frontend loadgenerator paymentservice productcatalogservice recommendationservice)
for ((i = 0; i < ${#WORKLOADS[@]}; i++)); do echo ${WORKLOADS[$i]}; done
```

Trying to find a generic way around this.

**Comment by malini-kamalambal** [comment]
Yes - This works in mac. See results below. But I think the index in mac might be starting at 1 instead of 0.

```
WORKLOADS=(cartservice checkoutservice currencyservice emailservice frontend loadgenerator paymentservice productcatalogservice recommendationservice)
for ((i = 0; i < ${#WORKLOADS[@]}; i++)); do echo ${WORKLOADS[$i]}; done

cartservice
checkoutservice
currencyservice
emailservice
frontend
loadgenerator
paymentservice
productcatalogservice
```

**Comment by mathieu-benoit** [comment]
Thanks for the info, I need to think about what could work best everywhere based on this. On Linux it starts at `0`.

**Comment by mathieu-benoit** [comment]
So I just documented a section `On Linux`, versus `On MacOS` for this part: https://github.com/mathieu-benoit/hello-humanitec/blob/main/docs/humanitec-default.md#on-macos.

Thanks for the feedback!
